In [21]:
import pandas as pd
import os

In [ ]:
encode = pd.read_csv("/cellar/users/aklie/data/datasets/tf_perturb_seq/datasets/ENCODE_WTC11_ChIP-seq/experiment_report.tsv", sep="\t", skiprows=1)
encode.head()

In [ ]:
benchmark = pd.read_csv("/cellar/users/aklie/data/datasets/tf_perturb_seq/datasets/ENCODE_WTC11_ChIP-seq/benchmark_tfs.tsv", sep="\t")

In [4]:
set(benchmark["Gene to perturb"]).intersection(set(encode["Target of assay"]))

{'AFF4', 'HMGA2', 'SMAD3', 'SMAD4', 'TCF7'}

In [5]:
canonical_tf = set(
    [
    "TFCP2L1",
    "KLF4",
    "MYC",
    "POU5F1",
    "SOX2",
    "ESRRB",
    "NANOG",
    "SALL4",
    "TBX3",
    "JARID2",
    "EZH2",
    "EED",
    "SUZ12",
    "HIF1A",
    "ARNT",
    "CTNNB1",
    "TCF7",
    "LEF1",
    "TCF7L1",
    "TCF7L2",
    "REST",
    "SMAD3",
    "SMAD4",
    "TCF12",
    "NFIB",
    "HDAC1",
    "AFF4",
    "KLF6",
    "HMGA2",
    "EP300",
    "CREBBP",
    "RUNX1",
    "BATF",
    "PAX5",
    "ARID1A",
    "ARID1B",
    "SMARCA2",
    "SMARCA4",
    "SMARCC1",
    "SMARCC2",
    "SMARCD1",
    "SMARCD2",
    "SMARCD3",
    "SMARCB1",
    "CLOCK",
    "ARNTL",
    ]
)

In [6]:
canonical_tf.intersection(set(encode["Target of assay"]))

{'AFF4', 'HMGA2', 'SMAD3', 'SMAD4', 'TCF7'}

In [8]:
overlap_tf = canonical_tf.intersection(set(encode["Target of assay"]))

In [9]:
overlap_tf

{'AFF4', 'HMGA2', 'SMAD3', 'SMAD4', 'TCF7'}

In [17]:
overlap_acc = encode[encode["Target of assay"].isin(overlap_tf)]["Accession"].values

In [19]:
path_bed = "/cellar/users/aklie/data/datasets/tf_perturb_seq/datasets/ENCODE_WTC11_ChIP-seq"
path_overlap = "/cellar/users/aklie/data/datasets/tf_perturb_seq/datasets/ENCODE_WTC11_ChIP-seq/overlap"

In [26]:
# Check in path bed for bed files corresponding to these accessions and move to overlap directory
for acc in overlap_acc:
    bed_file = os.path.join(path_bed, f"{acc}.bed.gz")
    if os.path.exists(bed_file):
        cmd = f"mv {bed_file} {path_overlap}/"
        print(cmd)
        #os.system(cmd)

In [24]:
bed_file

'/cellar/users/aklie/data/datasets/tf_perturb_seq/datasets/ENCODE_WTC11_ChIP-seq/ENCSR742DAU.bed.gz'

In [25]:
encode.columns

Index(['ID', 'Accession', 'Assay name', 'Assay title',
       'Biosample classification', 'Target', 'Target of assay',
       'Target gene symbol', 'Biosample summary', 'Biosample term name',
       'Dbxrefs', 'Description', 'Lab', 'Project', 'Status', 'Files',
       'Related series', 'Biosample accession', 'Biological replicate',
       'Technical replicate', 'Linked antibody', 'Organism', 'Life stage',
       'Biosample age', 'Biosample treatment',
       'Biosample treatment ontology ID', 'Biosample treatment amount',
       'Biosample treatment amount units', 'Biosample treatment duration',
       'Biosample treatment duration units', 'Synchronization',
       'Post-synchronization time', 'Post-synchronization time units',
       'Biosample modification site target organism',
       'Biosample modification site introduced gene organism', 'Replicates',
       'Mixed biosamples', 'Cellular component',
       'Library construction platform', 'Library construction method'],
      dtype='object')

In [ ]:
encode["ID"]

,ID,Accession,Assay name,Assay title,Biosample classification,Target,Target of assay,Target gene symbol,Biosample summary,Biosample term name,...,Synchronization,Post-synchronization time,Post-synchronization time units,Biosample modification site target organism,Biosample modification site introduced gene organism,Replicates,Mixed biosamples,Cellular component,Library construction platform,Library construction method
0,/experiments/ENCSR568LRK/,ENCSR568LRK,ChIP-seq,TF ChIP-seq,cell line,/targets/JAZF1-human/,JAZF1,JAZF1,Homo sapiens WTC11 genetically modified (inser...,WTC11,...,NaN,NaN,NaN,/organisms/human/,NaN,/replicates/fa924ad5-3340-4213-a0d3-9446f15597...,NaN,NaN,NaN,NaN
1,/experiments/ENCSR546PDE/,ENCSR546PDE,ChIP-seq,TF ChIP-seq,cell line,/targets/FOXP1-human/,FOXP1,FOXP1,Homo sapiens WTC11 genetically modified (inser...,WTC11,...,NaN,NaN,NaN,/organisms/human/,NaN,/replicates/55b84363-bc46-4526-9aa0-beb40785c8...,NaN,NaN,NaN,NaN
2,/experiments/ENCSR214RUE/,ENCSR214RUE,ChIP-seq,TF ChIP-seq,cell line,/targets/ZNF219-human/,ZNF219,ZNF219,Homo sapiens WTC11 genetically modified (inser...,WTC11,...,NaN,NaN,NaN,/organisms/human/,NaN,/replicates/3c1c31d6-a4c5-41cc-96ed-d253004b8d...,NaN,NaN,NaN,NaN
3,/experiments/ENCSR245QUM/,ENCSR245QUM,ChIP-seq,TF ChIP-seq,cell line,/targets/NFE2L1-human/,NFE2L1,NFE2L1,Homo sapiens WTC11 genetically modified (inser...,WTC11,...,NaN,NaN,NaN,/organisms/human/,NaN,/replicates/8809a14c-968a-4e1c-af39-c04a2018da...,NaN,NaN,NaN,NaN
4,/experiments/ENCSR700LFA/,ENCSR700LFA,ChIP-seq,TF ChIP-seq,cell line,/targets/CREB1-human/,CREB1,CREB1,Homo sapiens WTC11 genetically modified (inser...,WTC11,...,NaN,NaN,NaN,/organisms/human/,NaN,/replicates/444e430e-acb3-4dff-8c7d-b76bf876d7...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,/experiments/ENCSR288NNJ/,ENCSR288NNJ,ChIP-seq,TF ChIP-seq,cell line,/targets/ZNF416-human/,ZNF416,ZNF416,Homo sapiens WTC11 genetically modified (inser...,WTC11,...,NaN,NaN,NaN,/organisms/human/,NaN,/replicates/5caa8d51-3115-460f-bf5a-571cb1bac8...,NaN,NaN,NaN,NaN
86,/experiments/ENCSR373KKV/,ENCSR373KKV,ChIP-seq,TF ChIP-seq,cell line,/targets/ZNF138-human/,ZNF138,ZNF138,Homo sapiens WTC11 genetically modified (inser...,WTC11,...,NaN,NaN,NaN,/organisms/human/,NaN,/replicates/50e6f0a1-00ad-449a-96b5-4be2459fc0...,NaN,NaN,NaN,NaN
87,/experiments/ENCSR887VJM/,ENCSR887VJM,ChIP-seq,TF ChIP-seq,cell line,/targets/ATF1-human/,ATF1,ATF1,Homo sapiens WTC11 genetically modified (inser...,WTC11,...,NaN,NaN,NaN,/organisms/human/,NaN,/replicates/6c393608-f20e-4ff8-ac66-c38ad47d4d...,NaN,NaN,NaN,NaN
88,/experiments/ENCSR934WOF/,ENCSR934WOF,ChIP-seq,TF ChIP-seq,cell line,/targets/TEAD1-human/,TEAD1,TEAD1,Homo sapiens WTC11 genetically modified (inser...,WTC11,...,NaN,NaN,NaN,/organisms/human/,NaN,/replicates/9825918c-edba-47dd-a65a-816c2f45d0...,NaN,NaN,NaN,NaN
89,/experiments/ENCSR115QIT/,ENCSR115QIT,ChIP-seq,TF ChIP-seq,cell line,/targets/ZKSCAN8-human/,ZKSCAN8,ZKSCAN8,Homo sapiens WTC11 genetically modified (inser...,WTC11,...,NaN,NaN,NaN,/organisms/human/,NaN,/replicates/54f89bbb-d428-42dd-9971-43dc906fdf...,NaN,NaN,NaN,NaN

In [29]:
encode[encode["Accession"] == "ENCFF003OAO"]

Empty DataFrame
Columns: [ID, Accession, Assay name, Assay title, Biosample classification, Target, Target of assay, Target gene symbol, Biosample summary, Biosample term name, Dbxrefs, Description, Lab, Project, Status, Files, Related series, Biosample accession, Biological replicate, Technical replicate, Linked antibody, Organism, Life stage, Biosample age, Biosample treatment, Biosample treatment ontology ID, Biosample treatment amount, Biosample treatment amount units, Biosample treatment duration, Biosample treatment duration units, Synchronization, Post-synchronization time, Post-synchronization time units, Biosample modification site target organism, Biosample modification site introduced gene organism, Replicates, Mixed biosamples, Cellular component, Library construction platform, Library construction method]
Index: []

[0 rows x 40 columns]